usage              = "test"  #["build", "target", "classify", "test"] 
output_directory   = 'RB_out'
log_directory      = 'RB_out/logs'


[IBF]
kmer_size          = 15         #(unsigned integer with default 13) only required for 'usage = "build"' or if target_file/deplete_file is a fasta formate file 
fragment_size      = 100000     #(unsigned integer with default 100000)  only required for 'usage = "build" or if target_file/deplete_file is a fasta formate file 
threads            = 3          #(unsigned integer with default 3)
target_files  = ['path/to/reference/file/Bacillus_subtilis_complete_genome.fasta', 'path/to/reference/file/Enterococcus_faecalis_complete_genome.fasta', 'path/to/reference/file/Escherichia_coli_complete_genome.fasta']
deplete_files = ['path/to/reference/file/Saccharomyces_cerevisiae_draft_genome.fasta']
read_files    = ['path/to/read/file/SampleZMCDataSet.fasta']
exp_seq_error_rate = 0.1        #(unsigned float between 0 and 1 default 0.1)
chunk_length       = 360        #(unsigned integer with default 250)
max_chunks         = 1          #(unsigned integer with default 5)


[MinKNOW]
host               = "localhost" #(ip address or name of the computer hosting MinKNOW)
port               = "9502"      #(port number used fo grpc communication by by MinKNOW instance)
flowcell           = "MS00000"   #(name of the flowcell used)
token_path         = "test/tmp/minknow-auth-token.json"  #path/to/authentication/token/path (remote file)
channels           = [1,512]


[Basecaller]
caller             = "DeepNano" #DeepNano/Guppy (default is DeepNano)
host               = "127.0.0.1"#(ip address or name of the computer hosting Guppy Basecall Server)
port               = "9502"     #(port number on which the basecall server is running on the host)
threads            = 3          # (unsigned integer with default 3)
config             = "dna_r9.4.1_450bps_fast"


